# Generated by Django 5.0 on 2024-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('article_text', models.TextField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('article_name', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
    ]
