# Generated by Django 5.0 on 2024-01-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author_remove_article_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_count',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='title',
        ),
    ]
