name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          pip3 install -r requirements.txt
          ./manage.py test 
